# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-13 16:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductManager',
        ),
    ]
